name: advent_of_code_2022
description: Dart solutions of Advent of Code 2022
version: 1.0.0

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  path: ^1.8.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
